INSERT INTO COUNTRY (NAME, "LANGUAGE", TELEPHONE_CODE) VALUES ('Russia','Russian', '+7');
INSERT INTO COUNTRY (NAME, "LANGUAGE", TELEPHONE_CODE) VALUES ('Sweden','Swedish', '+58');
INSERT INTO COUNTRY (NAME, "LANGUAGE", TELEPHONE_CODE) VALUES ('UAE','Arabic', '+234');
INSERT INTO COUNTRY (NAME, "LANGUAGE", TELEPHONE_CODE) VALUES ('Belarus','Belarussian', '+33');

INSERT INTO CITY (NAME, POPULATION, CAPITAL, COUNTRY_ID) VALUES ('Moscow', 1400000, TRUE, SELECT ID FROM COUNTRY WHERE NAME = 'Russia');